name: Build and Deploy Angular App

on:
  workflow_dispatch:  # Adds a "Run workflow" button in Actions UI
    inputs:
      deployment_environment:
        description: 'Deployment environment to be used'
        required: true
        type: choice
        default: 'dev'
        options:  # Add others like 'staging', 'prod', etc... as they exist in the repo's "Environments"
          - dev
          - staging

env:
  NODE_VERSION: '20.x'
  PYTHON_VERSION: '3.12'
  APP_NAME: 'jv-frontend'

jobs:
  build-and-deploy:
    name: Build and Deploy

    # Points to the repo's "Environments": where `secrets.Xxx` will be accessed later on
    environment: ${{ github.event.inputs.deployment_environment }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular  # All `run:` steps will execute from `./angular` folder by default
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper versioning

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        # Full path from repo's root is required as I'm defining a `defaults.run.working-directory` at a custom location
        cache-dependency-path: 'angular/package-lock.json'

    - name: Install Node.js dependencies
      run: |
        echo "Making sure... ${{ env.AWS_REGION }}"
        echo "Making secrets... ${{ secrets.AWS_REGION }}"
        npm ci

    - name: Run tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Build Angular app
      run: |
        npm run build -- --configuration=production

    - name: Verify build output
      run: |
        echo "Checking for index.html:"
        find dist/*/browser/ -name "index.html" -type f

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:   # This action sets `env.AWS_Xxx` for next steps (in this case based on th "Environment" `secrets.Xxx`)
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Python deploy to S3 and CloudFront
      # The repo's "Environment" already brings `env.AWS_Xxx` as previously converted from `secrets.Xxx` so good to go
      # About `../` usages it's because of the `defaults.run.working-directory` definition at the `./angular` folder
      run: |
        python -m pip install --upgrade pip
        pip install -r ../scripts/requirements.txt
        python ../scripts/sync_to_s3.py \
          "dist/${{ env.APP_NAME }}/browser/" \
          "${{ env.APP_NAME }}-angular-app" \
          "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
